version: '3.8'

services:
  selenoid1:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid1
    hostname: selenoid1
    networks:
      - selenoid1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/vboxuser/selenoid/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid1 -limit 10

  selenoid2:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid2
    hostname: selenoid2
    networks:
      - selenoid2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/vboxuser/selenoid/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid2 -limit 10

  ggr:
    image: aerokube/ggr:1.7.2
    container_name: ggr
    hostname: ggr
    depends_on: [selenoid1, selenoid2]
    volumes:
      - /etc/grid-router/:/etc/grid-router:ro
    command: -guests-allowed -guests-quota "test" -verbose -quotaDir /etc/grid-router/quota
    networks:
      - selenoid1
      - selenoid2

  ggr_ui:
    image: aerokube/ggr-ui:1.2.0
    hostname: ggr_ui
    depends_on: [ggr]
    container_name: ggr-ui
    volumes:
      - /etc/grid-router/quota/:/etc/grid-router/quota:ro
    networks:
      - selenoid1
      - selenoid2

  selenoid_ui:
    image: aerokube/selenoid-ui:1.10.11
    hostname: selenoid_ui
    container_name: selenoid-ui
    depends_on: [ggr_ui]
    networks:
      - selenoid1
      - selenoid2
    command: --selenoid-uri http://ggr_ui:8888

  nginx:
    image: nginx:latest
    depends_on: [selenoid_ui, ggr]
    ports:
      - 80:80
    volumes:
      - /home/vboxuser/selenoid/nginx_common:/etc/nginx/conf.d:ro
    container_name: nginx
    hostname: nginx
    networks:
      - selenoid1
      - selenoid2
      - jenkins_default

  registry:
    image: registry:2.8.3
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./home/vboxuser/selenoid/registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/vboxuser/selenoid/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - JAVA_OPTS="-Dhudsson.model.DownloadService.noSignatureCheck=true"
      - DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins_default


networks:
  selenoid1:
    name: selenoid1
    external: true
  selenoid2:
    name: selenoid2
    external: true
  jenkins_default:
    name: jenkins_default
    external: true