FROM jenkins/agent:jdk21

USER root

RUN mkdir -p /root/jenkins_agent
WORKDIR /root/jenkins_agent

RUN apt-get update -y \
    && apt-get install -y wget unzip \
    && wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -P /tmp \
    && unzip /tmp/gradle-7.6-bin.zip -d /opt \
    && ln -s /opt/gradle-7.6/bin/gradle /usr/bin/gradle \
    && rm -rf /tmp/*

