FROM jenkins/agent:jdk21

USER root

RUN mkdir -p /root/jenkins_agent
WORKDIR /root/jenkins_agent

RUN apt-get update -y \
    && apt-get install -y wget python3 python3-pip python3-venv \
    && ln -s /usr/bin/python3 /usr/bin/python

RUN python3 -m pip install --break-system-packages --no-cache-dir jenkins-job-builder